### ISSUE TITLE
Unescape html special chatacters

### ISSUE THREAD

**Issue by sue445** [sue445/twittodon#26]
# Example
## Source tweet

![image](https://user-images.githubusercontent.com/608755/26880226-b5826500-4bce-11e7-9257-b6dfc3c8f631.png)

## Destination toot
![image](https://user-images.githubusercontent.com/608755/26880326-0bace676-4bcf-11e7-8752-d380fb0fc0cb.png)

Use `CGI.unescapeHTML`
https://docs.ruby-lang.org/ja/latest/method/CGI/s/unescapeHTML.html

**Comment by pooza** [comment]
昨日から使わせていただいてます。ありがとうございます。

アンエスケープが十分でないケースがまだある様です。
アンエスケープされないだけでなく、以降の文字列が削除されてしまうケースも。

https://twitter.com/pooza/status/875242250057338880
→ https://mstdn.b-shock.org/web/statuses/100000

https://twitter.com/pooza/status/875239983488966656
→ https://mstdn.b-shock.org/web/statuses/99985

https://twitter.com/pooza/status/875237065469771776
→ https://mstdn.b-shock.org/web/statuses/99974

ちょっと意地悪なケースなのでご報告すべきか迷いましたが、このBOTで一番重要な機能はここだと思うので、やはり報告させていただきました。
まだソースまでは読んでません。あと、英語じゃなくてごめんなさい。

**Comment by sue445** [comment]
@pooza 報告ありがとうございます。

https://mstdn.b-shock.org/ はログインしてないと見れないのでスクショかテキストで貼ってもらってもいいでしょうか？

**Comment by pooza** [comment]
おっと、ログインが必要でしたね。失礼しました。

https://twitter.com/pooza/status/875237065469771776
<img width="303" alt="https mstdn b-shock org web statuses 99974" src="https://user-images.githubusercontent.com/995262/27205470-fd70ee4c-526b-11e7-8394-a7c6031b8a4c.png">

https://twitter.com/pooza/status/875239983488966656
<img width="308" alt="https mstdn b-shock org web statuses 99985" src="https://user-images.githubusercontent.com/995262/27205471-fd96e2e6-526b-11e7-86f6-ba16212ff3f5.png">

https://twitter.com/pooza/status/875242250057338880
<img width="304" alt="https mstdn b-shock org web statuses 100000" src="https://user-images.githubusercontent.com/995262/27205472-fd994806-526b-11e7-8dfe-765e695c0d0d.png">

追加で、こんなのも。
https://twitter.com/pooza/status/875480815785738240
<img width="320" alt="2017-06-16 8 18 36" src="https://user-images.githubusercontent.com/995262/27205549-70740e92-526c-11e7-8beb-862195325913.png">
これはHTMLのエスケープとは無関係なので、Issueを分けたほうがいいでしょうか。

**Comment by sue445** [comment]
関係してないことはないのでissue自体は一緒でもいいかと思ってましたが返事する前に #29 が作られたのでこっちは再度クローズします
