### ISSUE TITLE
Bug: mis removed words following shorten url

### ISSUE THREAD

**Issue by pooza** [sue445/twittodon#29]
別件ですので、Issue分けました。
必要でしたら、タイトルは適当に修正してください＞＜

https://twitter.com/pooza/status/875480815785738240
<img width="320" alt="27205549-70740e92-526c-11e7-8beb-862195325913" src="https://user-images.githubusercontent.com/995262/27207005-50d9a808-5276-11e7-8387-ab99abe97ca6.png">

https://twitter.com/pooza/status/875503517322149888
<img width="317" alt="2017-06-16 9 29 53" src="https://user-images.githubusercontent.com/995262/27207018-6696acf4-5276-11e7-9e12-0057716ab405.png">

後者は、先ほど発生したケース。
現象としては同じですが、どこまで削除されているかをみれば切り分けに役立つと思ったので上げました。

**Comment by sue445** [comment]
@pooza 遅くなりましたが報告あったバグ直しました

twittodonのtweetサニタイズ処理をgem化してそこでバグ修正してます。
https://github.com/sue445/tweet_sanitizer

報告あったツイートに関してはテストコード上で修正確認してます

* https://github.com/sue445/tweet_sanitizer/blob/v0.1.0/spec/tweet_sanitizer_spec.rb
* https://github.com/sue445/tweet_sanitizer/blob/v0.1.0/spec/support/utils/stub_util.rb

**Comment by pooza** [comment]
@sue445 修正ありがとうございます。おつかれさまでした！
当方の環境への適用等、一両日ぐらいに対応させて頂きます。

また、gem化についてもありがとうございます。
こちらも、早速使わせていただくことになりそうです。

**Comment by pooza** [comment]
@sue445 簡単にですが、修正されたことを確認しました。おつかれさまでした。
